name: Cypress Tests

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, labeled]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run dev
          working-directory: ./client
      - name: Run Component Testing
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run dev
          working-directory: ./client
          install: false
          component: true
        env:
          CYPRESS_BASE_URL: https://ai-airbnb.vercel.app
